import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import prisma from '@/lib/db';

interface RouteParams {
  params: Promise<{ examId: string }>;
}

// GET /api/exams/[examId]/export - Export exam as LaTeX
export async function GET(request: Request, { params }: RouteParams) {
  try {
    const session = await getServerSession(authOptions);
    const { examId } = await params;

    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const includeSolutions = searchParams.get('solutions') === 'true';

    const exam = await prisma.exam.findFirst({
      where: {
        id: examId,
        userId: session.user.id,
      },
      include: {
        course: { select: { code: true, name: true } },
        examType: { select: { name: true } },
        examQuestions: {
          orderBy: { questionOrder: 'asc' },
          include: {
            question: {
              include: {
                options: { orderBy: { sortOrder: 'asc' } },
              },
            },
          },
        },
      },
    });

    if (!exam) {
      return NextResponse.json({ error: 'Exam not found' }, { status: 404 });
    }

    // Generate LaTeX
    const latex = generateExamLatex(exam, includeSolutions);

    // Return as downloadable file
    const filename = `${exam.course.code}_${exam.examType.name}_${exam.academicYear || 'exam'}.tex`
      .replace(/\s+/g, '_')
      .toLowerCase();

    return new NextResponse(latex, {
      headers: {
        'Content-Type': 'application/x-tex',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Error exporting exam:', error);
    return NextResponse.json(
      { error: 'Failed to export exam' },
      { status: 500 }
    );
  }
}

function generateExamLatex(exam: any, includeSolutions: boolean): string {
  const totalPoints = exam.examQuestions.reduce(
    (sum: number, eq: any) => sum + (eq.pointsAssigned ? Number(eq.pointsAssigned) : 0),
    0
  );

  let latex = `% ${exam.title}
% Generated by Exam Manager
% Course: ${exam.course.code} - ${exam.course.name}
% Type: ${exam.examType.name}
${exam.academicYear ? `% Year: ${exam.academicYear}${exam.semester ? ` ${exam.semester}` : ''}` : ''}
% Total Points: ${totalPoints}

\\documentclass[11pt,a4paper]{article}

% Packages
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath,amssymb,amsthm}
\\usepackage{geometry}
\\usepackage{fancyhdr}
\\usepackage{enumitem}
\\usepackage{graphicx}
\\usepackage{float}
\\usepackage{parskip}

% Page geometry
\\geometry{
  top=2.5cm,
  bottom=2.5cm,
  left=2.5cm,
  right=2.5cm
}

% Header/Footer
\\pagestyle{fancy}
\\fancyhf{}
\\lhead{${escapeLatex(exam.course.code)}}
\\chead{${escapeLatex(exam.examType.name)}}
\\rhead{${exam.academicYear ? `${exam.academicYear}${exam.semester ? ` ${exam.semester}` : ''}` : ''}}
\\rfoot{Page \\thepage}

% Custom commands
\\newcommand{\\points}[1]{\\hfill[#1 points]}
\\newcommand{\\examtitle}[1]{\\begin{center}\\Large\\textbf{#1}\\end{center}}
\\newcommand{\\instructions}[1]{\\begin{center}\\begin{minipage}{0.9\\textwidth}#1\\end{minipage}\\end{center}\\vspace{1em}}

\\begin{document}

% Title
\\examtitle{${escapeLatex(exam.title)}}

% Course and exam info
\\begin{center}
\\textbf{${escapeLatex(exam.course.code)} -- ${escapeLatex(exam.course.name)}}\\\\[0.5em]
${exam.examDate ? `Date: ${new Date(exam.examDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\\\\[0.3em]` : ''}
${exam.durationMinutes ? `Duration: ${exam.durationMinutes} minutes\\\\[0.3em]` : ''}
Total Points: ${totalPoints}
\\end{center}

\\vspace{1em}
\\hrule
\\vspace{1em}

% Student info
\\noindent\\textbf{Name:} \\underline{\\hspace{6cm}} \\hfill \\textbf{ID:} \\underline{\\hspace{4cm}}

\\vspace{1em}

`;

  // Instructions
  if (exam.instructionsLatex) {
    latex += `% Instructions
\\instructions{
${exam.instructionsLatex}
}

\\vspace{1em}
\\hrule
\\vspace{1em}

`;
  }

  // Questions
  latex += `% Questions
\\begin{enumerate}[leftmargin=*]

`;

  exam.examQuestions.forEach((eq: any, index: number) => {
    const question = eq.question;
    const points = eq.pointsAssigned ? Number(eq.pointsAssigned) : 0;

    latex += `% Question ${index + 1}
\\item `;

    // Add points indicator
    if (points > 0) {
      latex += `\\points{${points}}\n\n`;
    } else {
      latex += '\n\n';
    }

    // Question text
    latex += `${question.questionLatex}\n\n`;

    // Multiple choice options
    if (question.questionType === 'MULTIPLE_CHOICE' && question.options.length > 0) {
      latex += `\\begin{enumerate}[label=(\\Alph*)]\n`;
      question.options.forEach((opt: any) => {
        latex += `  \\item ${opt.optionLatex}\n`;
      });
      latex += `\\end{enumerate}\n\n`;
    }

    // Add space for answer
    if (question.questionType === 'SHORT_ANSWER') {
      latex += `\\vspace{3cm}\n\n`;
    } else if (question.questionType === 'LONG_FORM') {
      latex += `\\vspace{6cm}\n\n`;
    } else if (question.questionType === 'NUMERICAL') {
      latex += `\\vspace{2cm}\n\n`;
    }

    latex += `\\vspace{1em}\n\n`;
  });

  latex += `\\end{enumerate}

\\end{document}
`;

  // If solutions requested, generate a separate solutions section
  if (includeSolutions) {
    latex = generateExamWithSolutions(exam, latex, totalPoints);
  }

  return latex;
}

function generateExamWithSolutions(exam: any, examLatex: string, totalPoints: number): string {
  // Add solutions document after the exam
  let solutionsLatex = `

% ============================================
% SOLUTIONS
% ============================================

\\newpage
\\examtitle{${escapeLatex(exam.title)} -- SOLUTIONS}

\\begin{center}
\\textbf{${escapeLatex(exam.course.code)} -- ${escapeLatex(exam.course.name)}}\\\\[0.5em]
Total Points: ${totalPoints}
\\end{center}

\\vspace{1em}
\\hrule
\\vspace{1em}

\\begin{enumerate}[leftmargin=*]

`;

  exam.examQuestions.forEach((eq: any, index: number) => {
    const question = eq.question;
    const points = eq.pointsAssigned ? Number(eq.pointsAssigned) : 0;

    solutionsLatex += `% Solution ${index + 1}
\\item `;

    if (points > 0) {
      solutionsLatex += `\\points{${points}}\n\n`;
    } else {
      solutionsLatex += '\n\n';
    }

    // Show answer key
    if (question.questionType === 'MULTIPLE_CHOICE') {
      const correctOption = question.options.find((opt: any) => opt.isCorrect);
      if (correctOption) {
        solutionsLatex += `\\textbf{Answer: (${correctOption.label})} ${correctOption.optionLatex}\n\n`;
      }
    } else if (question.answerKey) {
      solutionsLatex += `\\textbf{Answer:} ${question.answerKey}\n\n`;
    }

    // Show full solution if available
    if (question.solutionLatex) {
      solutionsLatex += `\\textbf{Solution:}\n\n${question.solutionLatex}\n\n`;
    }

    solutionsLatex += `\\vspace{1em}\n\\hrule\n\\vspace{1em}\n\n`;
  });

  solutionsLatex += `\\end{enumerate}

\\end{document}
`;

  // Insert solutions before the final \end{document}
  return examLatex.replace('\\end{document}', solutionsLatex);
}

function escapeLatex(text: string): string {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}
